language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: ['g++-8']
      env: COMPILER='g++-8'

    - os: windows

install:
  # Download and install cmake 3.15
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.15/cmake-3.15.6-Linux-x86_64.tar.gz"
      mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
      export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}
    fi

before_script:
  - export CXX=${COMPILER}

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
