name: Release header file

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      contents: write
    name: Publish header
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: include/argparse.hpp
